### ISSUE TITLE
WordPress 4.7 refactored wp_get_object_terms issues

### ISSUE THREAD

**Issue by ppetrov2create** [tyxla/carbon-breadcrumbs#34]
Carbon_Breadcrumb_Trail_Setup.php - populate_category_items

`$categories = wp_get_object_terms( get_the_ID(), $taxonomy, 'orderby=term_id' );`

should be updated to

`$categories = wp_get_object_terms( get_the_ID(), $taxonomy, array( 'orderby' => 'term_id' ) );`

**Comment by tyxla** [comment]
Thanks for the bug report! 👍 

While I agree the array method is the preferred one, string `$args` should still be supported by the core. 

String `$args` are not supported in 4.7 because of bug, introduced in: https://core.trac.wordpress.org/changeset/38667 and this caused the bug you're reporting.

This issue has already been reported and fixed in the core, and will be included in 4.7.1 and future versions:
* Ticket: https://core.trac.wordpress.org/ticket/39215
* Changeset: https://core.trac.wordpress.org/changeset/39578

In any case, using the array here is recommended, so I'll leave this one open.

Pull request for this should be rather straightforward, feel free to submit one @ppetrov2create! 😉

**Comment by Stoyan0v** [comment]
Fixed in #35
